import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google'

export const metadata: Metadata = {
  title: "Next Exercicios",
  description: "Generated by create next app",
};

const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "400", "600", "800"]
})

export default function RootLayout({ children, }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`antialiased`}>
        {children}
      </body>
    </html>
  );
}
